services:
  kratos:
    image: ${KRATOS_IMAGE}
    container_name: mojaly-rafiki-kratos
    privileged: true
    environment:
      DSN: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/${KRATOS_DATABASE_NAME}?sslmode=disable&max_conns=20&max_idle_conns=4
      SECRETS_COOKIE_0: ${KRATOS_COOKIE_SECRET}
      SECRETS_CIPHER_0: ${KRATOS_CIPHER_SECRET}
      COURIER_SMTP_CONNECTION_URI: ${KRATOS_SMTP_CONNECTION_URI}
      SERVE_PUBLIC_BASE_URL: ${KRATOS_PUBLIC_URL}
      SELFSERVICE_DEFAULT_BROWSER_RETURN_URL: ${KRATOS_BROWSER_URL}/
      SELFSERVICE_ALLOWED_RETURN_URLS_0: ${KRATOS_BROWSER_URL}
      SELFSERVICE_METHODS_LINK_CONFIG_BASE_URL: ${KRATOS_LINK_BASE_URL}
      SELFSERVICE_FLOWS_ERROR_UI_URL: ${KRATOS_ERROR_UI_URL}
      SELFSERVICE_FLOWS_SETTINGS_UI_URL: ${KRATOS_SETTINGS_UI_URL}
      SELFSERVICE_FLOWS_RECOVERY_UI_URL: ${KRATOS_RECOVERY_UI_URL}
      SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL: ${KRATOS_LOGOUT_RETURN_URL}
      SELFSERVICE_FLOWS_LOGIN_UI_URL: ${KRATOS_LOGIN_UI_URL}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4433:4433"
      - "4434:4434"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./identity.schema.json:/etc/config/kratos/identity.schema.json
      - ${KRATOS_CONFIG_FILE:-./kratos.yml}:/etc/config/kratos/kratos.yml
    entrypoint: ["/entrypoint.sh"]
    networks:
      - rafiki
