version: v0.13.0

serve:
  public:
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  methods:
    link:
      config:
        lifespan: 1h
      enabled: true
    password:
      enabled: true

  flows:
    settings:
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      use: link
      after:
        hooks:
          - hook: revoke_active_sessions

    verification:
      enabled: false

    login:
      lifespan: 10m

    registration:
      enabled: false

log:
  level: info
  format: json
  leak_sensitive_values: false

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 10

identity:
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

session:
  lifespan: 1h
  cookie:
    persistent: false
    same_site: Strict
    path: /
